/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '//': RouteRecordInfo<'//', '/', Record<never, never>, Record<never, never>>,
    '//beranda': RouteRecordInfo<'//beranda', '/beranda', Record<never, never>, Record<never, never>>,
    '//beranda/': RouteRecordInfo<'//beranda/', '/beranda', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/auth': RouteRecordInfo<'/auth', '/auth', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/login-2': RouteRecordInfo<'/auth/login-2', '/auth/login-2', Record<never, never>, Record<never, never>>,
    '/auth/login-3': RouteRecordInfo<'/auth/login-3', '/auth/login-3', Record<never, never>, Record<never, never>>,
    '/auth/signup-1': RouteRecordInfo<'/auth/signup-1', '/auth/signup-1', Record<never, never>, Record<never, never>>,
    '/auth/signup-2': RouteRecordInfo<'/auth/signup-2', '/auth/signup-2', Record<never, never>, Record<never, never>>,
    '/auth/signup-3': RouteRecordInfo<'/auth/signup-3', '/auth/signup-3', Record<never, never>, Record<never, never>>,
    '/error': RouteRecordInfo<'/error', '/error', Record<never, never>, Record<never, never>>,
    '/error/page-1': RouteRecordInfo<'/error/page-1', '/error/page-1', Record<never, never>, Record<never, never>>,
    '/error/page-2': RouteRecordInfo<'/error/page-2', '/error/page-2', Record<never, never>, Record<never, never>>,
    '/error/page-3': RouteRecordInfo<'/error/page-3', '/error/page-3', Record<never, never>, Record<never, never>>,
    '/error/page-4': RouteRecordInfo<'/error/page-4', '/error/page-4', Record<never, never>, Record<never, never>>,
    '/error/page-5': RouteRecordInfo<'/error/page-5', '/error/page-5', Record<never, never>, Record<never, never>>,
    '/guard': RouteRecordInfo<'/guard', '/guard', Record<never, never>, Record<never, never>>,
    '/guard/cheklis-kendaraan': RouteRecordInfo<'/guard/cheklis-kendaraan', '/guard/cheklis-kendaraan', Record<never, never>, Record<never, never>>,
    '/guard/cheklis-kendaraan/cit': RouteRecordInfo<'/guard/cheklis-kendaraan/cit', '/guard/cheklis-kendaraan/cit', Record<never, never>, Record<never, never>>,
    '/guard/cheklis-kendaraan/form-cheklis-cit/[formchekliscit]': RouteRecordInfo<'/guard/cheklis-kendaraan/form-cheklis-cit/[formchekliscit]', '/guard/cheklis-kendaraan/form-cheklis-cit/:formchekliscit', { formchekliscit: ParamValue<true> }, { formchekliscit: ParamValue<false> }>,
    '/guard/cheklis-kendaraan/form-cheklis-rpl/[formcheklisrpl]': RouteRecordInfo<'/guard/cheklis-kendaraan/form-cheklis-rpl/[formcheklisrpl]', '/guard/cheklis-kendaraan/form-cheklis-rpl/:formcheklisrpl', { formcheklisrpl: ParamValue<true> }, { formcheklisrpl: ParamValue<false> }>,
    '/guard/cheklis-kendaraan/rpl': RouteRecordInfo<'/guard/cheklis-kendaraan/rpl', '/guard/cheklis-kendaraan/rpl', Record<never, never>, Record<never, never>>,
    '/konfigurasi': RouteRecordInfo<'/konfigurasi', '/konfigurasi', Record<never, never>, Record<never, never>>,
    '/konfigurasi/akun': RouteRecordInfo<'/konfigurasi/akun', '/konfigurasi/akun', Record<never, never>, Record<never, never>>,
    '/konfigurasi/akun/form-group-akses-add': RouteRecordInfo<'/konfigurasi/akun/form-group-akses-add', '/konfigurasi/akun/form-group-akses-add', Record<never, never>, Record<never, never>>,
    '/konfigurasi/akun/form-group-akses-edit/[formgroupaksesedit]': RouteRecordInfo<'/konfigurasi/akun/form-group-akses-edit/[formgroupaksesedit]', '/konfigurasi/akun/form-group-akses-edit/:formgroupaksesedit', { formgroupaksesedit: ParamValue<true> }, { formgroupaksesedit: ParamValue<false> }>,
    '/konfigurasi/akun/form-pengguna-add': RouteRecordInfo<'/konfigurasi/akun/form-pengguna-add', '/konfigurasi/akun/form-pengguna-add', Record<never, never>, Record<never, never>>,
    '/konfigurasi/akun/form-pengguna-edit/[formpenggunaedit]': RouteRecordInfo<'/konfigurasi/akun/form-pengguna-edit/[formpenggunaedit]', '/konfigurasi/akun/form-pengguna-edit/:formpenggunaedit', { formpenggunaedit: ParamValue<true> }, { formpenggunaedit: ParamValue<false> }>,
    '/konfigurasi/akun/group-akses': RouteRecordInfo<'/konfigurasi/akun/group-akses', '/konfigurasi/akun/group-akses', Record<never, never>, Record<never, never>>,
    '/konfigurasi/akun/pengguna': RouteRecordInfo<'/konfigurasi/akun/pengguna', '/konfigurasi/akun/pengguna', Record<never, never>, Record<never, never>>,
    '/konfigurasi/master-data': RouteRecordInfo<'/konfigurasi/master-data', '/konfigurasi/master-data', Record<never, never>, Record<never, never>>,
    '/konfigurasi/master-data/form-mobil-add': RouteRecordInfo<'/konfigurasi/master-data/form-mobil-add', '/konfigurasi/master-data/form-mobil-add', Record<never, never>, Record<never, never>>,
    '/konfigurasi/master-data/form-mobil-edit/[formmobiledit]': RouteRecordInfo<'/konfigurasi/master-data/form-mobil-edit/[formmobiledit]', '/konfigurasi/master-data/form-mobil-edit/:formmobiledit', { formmobiledit: ParamValue<true> }, { formmobiledit: ParamValue<false> }>,
    '/konfigurasi/master-data/master-cabang': RouteRecordInfo<'/konfigurasi/master-data/master-cabang', '/konfigurasi/master-data/master-cabang', Record<never, never>, Record<never, never>>,
    '/konfigurasi/master-data/master-mobil': RouteRecordInfo<'/konfigurasi/master-data/master-mobil', '/konfigurasi/master-data/master-mobil', Record<never, never>, Record<never, never>>,
    '/laporan': RouteRecordInfo<'/laporan', '/laporan', Record<never, never>, Record<never, never>>,
    '/laporan/laporan-guard': RouteRecordInfo<'/laporan/laporan-guard', '/laporan/laporan-guard', Record<never, never>, Record<never, never>>,
    '/laporan/laporan-guard/form-laporan-cheklis-cit': RouteRecordInfo<'/laporan/laporan-guard/form-laporan-cheklis-cit', '/laporan/laporan-guard/form-laporan-cheklis-cit', Record<never, never>, Record<never, never>>,
    '/laporan/laporan-guard/form-laporan-cheklis-rpl': RouteRecordInfo<'/laporan/laporan-guard/form-laporan-cheklis-rpl', '/laporan/laporan-guard/form-laporan-cheklis-rpl', Record<never, never>, Record<never, never>>,
  }
}
