/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '//': RouteRecordInfo<'//', '/', Record<never, never>, Record<never, never>>,
    '//beranda': RouteRecordInfo<'//beranda', '/beranda', Record<never, never>, Record<never, never>>,
    '//beranda/': RouteRecordInfo<'//beranda/', '/beranda', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/auth': RouteRecordInfo<'/auth', '/auth', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/error': RouteRecordInfo<'/error', '/error', Record<never, never>, Record<never, never>>,
    '/error/page-1': RouteRecordInfo<'/error/page-1', '/error/page-1', Record<never, never>, Record<never, never>>,
    '/error/page-2': RouteRecordInfo<'/error/page-2', '/error/page-2', Record<never, never>, Record<never, never>>,
    '/error/page-3': RouteRecordInfo<'/error/page-3', '/error/page-3', Record<never, never>, Record<never, never>>,
    '/error/page-4': RouteRecordInfo<'/error/page-4', '/error/page-4', Record<never, never>, Record<never, never>>,
    '/error/page-5': RouteRecordInfo<'/error/page-5', '/error/page-5', Record<never, never>, Record<never, never>>,
    '/konfigurasi': RouteRecordInfo<'/konfigurasi', '/konfigurasi', Record<never, never>, Record<never, never>>,
    '/konfigurasi/akun': RouteRecordInfo<'/konfigurasi/akun', '/konfigurasi/akun', Record<never, never>, Record<never, never>>,
    '/konfigurasi/akun/form-group-akses-add': RouteRecordInfo<'/konfigurasi/akun/form-group-akses-add', '/konfigurasi/akun/form-group-akses-add', Record<never, never>, Record<never, never>>,
    '/konfigurasi/akun/form-group-akses-edit/[formgroupaksesedit]': RouteRecordInfo<'/konfigurasi/akun/form-group-akses-edit/[formgroupaksesedit]', '/konfigurasi/akun/form-group-akses-edit/:formgroupaksesedit', { formgroupaksesedit: ParamValue<true> }, { formgroupaksesedit: ParamValue<false> }>,
    '/konfigurasi/akun/form-pengguna-add': RouteRecordInfo<'/konfigurasi/akun/form-pengguna-add', '/konfigurasi/akun/form-pengguna-add', Record<never, never>, Record<never, never>>,
    '/konfigurasi/akun/form-pengguna-edit/[formpenggunaedit]': RouteRecordInfo<'/konfigurasi/akun/form-pengguna-edit/[formpenggunaedit]', '/konfigurasi/akun/form-pengguna-edit/:formpenggunaedit', { formpenggunaedit: ParamValue<true> }, { formpenggunaedit: ParamValue<false> }>,
    '/konfigurasi/akun/group-akses': RouteRecordInfo<'/konfigurasi/akun/group-akses', '/konfigurasi/akun/group-akses', Record<never, never>, Record<never, never>>,
    '/konfigurasi/akun/pengguna': RouteRecordInfo<'/konfigurasi/akun/pengguna', '/konfigurasi/akun/pengguna', Record<never, never>, Record<never, never>>,
    '/konfigurasi/master-data': RouteRecordInfo<'/konfigurasi/master-data', '/konfigurasi/master-data', Record<never, never>, Record<never, never>>,
    '/konfigurasi/master-data/poli': RouteRecordInfo<'/konfigurasi/master-data/poli', '/konfigurasi/master-data/poli', Record<never, never>, Record<never, never>>,
    '/pelayanan': RouteRecordInfo<'/pelayanan', '/pelayanan', Record<never, never>, Record<never, never>>,
    '/pelayanan/rajal': RouteRecordInfo<'/pelayanan/rajal', '/pelayanan/rajal', Record<never, never>, Record<never, never>>,
    '/pelayanan/rajal/': RouteRecordInfo<'/pelayanan/rajal/', '/pelayanan/rajal', Record<never, never>, Record<never, never>>,
    '/pelayanan/rajal/form-pasien-add': RouteRecordInfo<'/pelayanan/rajal/form-pasien-add', '/pelayanan/rajal/form-pasien-add', Record<never, never>, Record<never, never>>,
    '/pelayanan/rajal/form-pasien-edit/[formpasienedit]': RouteRecordInfo<'/pelayanan/rajal/form-pasien-edit/[formpasienedit]', '/pelayanan/rajal/form-pasien-edit/:formpasienedit', { formpasienedit: ParamValue<true> }, { formpasienedit: ParamValue<false> }>,
  }
}
